# Generated by Django 5.1.2 on 2024-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='chat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
